[project]
name = "uma-engine"
authors = ["UMA Development Team"]
description = "Universal Marketplace Accelerator for Decentralized Commerce"
telemetry = false
requirements = []
[contracts.universal-market]
path = "contracts/universal-market.clar"
depends_on = []

[contracts.financial-processor]
path = "contracts/financial-processor.clar"
depends_on = []

[contracts.trust-verification]
path = "contracts/trust-verification.clar"
depends_on = []

[contracts.transaction-optimizer]
path = "contracts/transaction-optimizer.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
